name = "MPCCBenchmark"
uuid = "73e39df8-f0b4-4047-96d4-8c5f970303c6"
version = "0.1.0"

[deps]
ExaPowerIO = "14903efe-9500-4d7f-a589-7ab7e15da6de"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ExaPowerIO = "0.3.0"
JuMP = "1"
LinearAlgebra = "1.11.0"
